- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  ignore_errors: true
  
- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes
