# Désactivation de l'IPv6 sur un système GNU/Linux
---
- name: Désactiver l'IPv6 dans sysctl.conf
  block:
    - name: Assurer que les paramètres IPv6 sont configurés dans /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv6.conf.default.disable_ipv6'
        line: 'net.ipv6.conf.default.disable_ipv6 = 1'
        state: present

    - name: Assurer que les paramètres IPv6 sont configurés dans /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv6.conf.all.disable_ipv6'
        line: 'net.ipv6.conf.all.disable_ipv6 = 1'
        state: present

    - name: Appliquer les paramètres sysctl
      command: sysctl -p

- name: Redémarrer le système pour appliquer les changements
  reboot:
    msg: "Redémarrage du système pour désactiver l'IPv6"
    reboot_timeout: 60

