
# [R3] Activer le démarrage sécurisé UEFI

---
- name: Install mokutil
  ansible.builtin.dnf:
    name: mokutil
    state: present
    
- name: Ensure UEFI Secure Boot is enabled
  command: mokutil --sb-state
  register: secure_boot_status
  ignore_errors: yes

- name: Check if Secure Boot is enabled
  debug:
    msg: "Secure Boot is enabled."
  when: "'SecureBoot enabled' in secure_boot_status.stdout"

- name: Notify that Secure Boot is not enabled
  debug:
    msg: "Secure Boot is not enabled. Please enable it in the BIOS/UEFI settings."
  when: "'SecureBoot enabled' not in secure_boot_status.stdout"