- name: Retrieve the list of running processes
  command: ps aux
  register: processes_info

- name: Processes
  block:
    - name: Show list of running processes
      debug:
        msg: "The list of running processes is : {{ processes_info.stdout_lines }}"
      when: LANGUAGE.user_input == "english"

    - name: Afficher la liste des processus en cours
      debug:
        msg: "La liste des processus en cours est : {{ processes_info.stdout_lines }}"
      when: LANGUAGE.user_input == "french"
  when: GATHER_INFO_VIEW.user_input == "oui" or GATHER_INFO_VIEW.user_input == "yes"
