- name: Retrieve information about network interfaces
  command: ip a
  register: network_info
  
- name: Network
  block:
    - name: View network interface information
      debug:
        msg: "Information about network interfaces is : {{ network_info.stdout_lines }}"
      when: LANGUAGE.user_input == "english"

    - name: Afficher les informations sur les interfaces réseau
      debug:
        msg: "Les informations sur les interfaces réseau sont : {{ network_info.stdout_lines }}"
      when: LANGUAGE.user_input == "french"
  when: GATHER_INFO_VIEW.user_input == "oui" or GATHER_INFO_VIEW.user_input == "yes"
