- name: Retrieve memory information
  command: free -m
  register: memory_info

- name: Memory
  block:
    - name: Show memory information
      debug:
        msg: "Memory information is : {{ memory_info.stdout_lines }}"
      when: LANGUAGE.user_input == "english"

    - name: Afficher les informations sur la mémoire
      debug:
        msg: "Les informations sur la mémoire sont : {{ memory_info.stdout_lines }}"
      when: LANGUAGE.user_input == "french"
  when: GATHER_INFO_VIEW.user_input == "oui" or GATHER_INFO_VIEW.user_input == "yes"
